---
- name: lancer spark-submit
  hosts: masternode
  tasks:
    - name: envoi tp2
      ansible.builtin.copy:
        src: files/tp2
        dest: /home/ubuntu/spark
        mode: '0644'
    - name: envoi script
      ansible.builtin.copy:
        src: files/submit.sh
        dest: /home/ubuntu/spark/tp2/tpSpark
        mode: '0644'
    - name: lancer script
      ansible.builtin.command:
        cmd: sh /home/ubuntu/spark/tp2/tpSpark/submit.sh

